### ISSUE TITLE
Copyright and Usage Example

### ISSUE THREAD

**Issue by neutrous** [Haskkor/react-native-pincode#11]
First, thanks for your great PinCode component, it looks fantastic 👍.
However, owing to the lack of a copyright statement, it makes me stop the pace to use it in a potential commercial product.
If that not be a problem, would you please give a simple Example of how to use this component? Suppose using this component in a single screen, combined with _react-navigation_, how could I navigate to another screen after **successfully PIN CODE** input?

**Comment by Haskkor** [comment]
Hi!

I added the licence, sorry for that :). Feel free to use it anyway you want.
To navigate to a new page after a successful input, you can use the **finishProcess** props.
So on a basic usage it could look like this:

```
    return (
      <View style={styles.container}>
        <PINCode
          status={'enter'}
          finishProcess={() => this.props.navigation.navigate('StaticHelpNonBiometrics')}/>
      </View>
    )
```

As the navigation to the new page is triggered on the last digit press, you could add a small delay to have something less ugly :).

```
 return (
      <View style={styles.container}>
        <PINCode
          status={'enter'}
          finishProcess={async () => {
            await delay(500)
            this.props.navigation.navigate('StaticHelpNonBiometrics')
          }}/>
      </View>
    )
```

Cheers

**Comment by neutrous** [comment]
Thanks for your quick reply 😎
