### ISSUE TITLE
Unhandled Promise Rejection: setGenericPasswordForOptions

### ISSUE THREAD

**Issue by mikecann** [Haskkor/react-native-pincode#12]
Hey,

Firstly awesome component mate, very good work.

I am testing it in the simulator and it works great except for the final part once the key is confirmed I get an exception: 

```
Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'setGenericPasswordForOptions' of undefined
TypeError: Cannot read property 'setGenericPasswordForOptions' of undefined
    at Object.setGenericPassword (blob:http://localhost:8081/1f2ec60d-926f-43e9-b4a3-564cdc3a4f6e:203342:30)
    at PinCodeChoose._callee$ (blob:http://localhost:8081/1f2ec60d-926f-43e
...
```

I suspect it is to do with https://github.com/oblador/react-native-keychain but cant for the life of me work out why its not working.

Does one have to install `react-native-keychain` explicitly or is just `react-native-pincode`'s dependency on it good enough?

**Comment by mikecann** [comment]
Maybe something to do with this? https://github.com/oblador/react-native-keychain/issues/84

**Comment by mikecann** [comment]
Okay looks like I have fixed this error by following the manual linking instructions here: https://github.com/oblador/react-native-keychain hopefully thats a help to someone

**Comment by Haskkor** [comment]
I've put this on the readme:

<img width="692" alt="screen shot 2018-07-13 at 8 34 36 am" src="https://user-images.githubusercontent.com/10620919/42657856-a3deac48-8677-11e8-9ed9-633bfa9a4fd8.png">

I'm sorry that you lost time because it's not clear enough. I'll try to find a way to make this more explicit :).

Thanks for your feedback!
