### ISSUE TITLE
Callback when pin has been chosen?

### ISSUE THREAD

**Issue by mikecann** [Haskkor/react-native-pincode#13]
Maybe im missing something obvious but I cant seem to work out how I am supposed to get an event / callback when the user has chosen a pin (status is "choose"). 

The "finishProcess" callback seems to only be triggered after the user has entered the pin when the status is "enter".

**Comment by Panda-ref** [comment]
You can use `storePin={pin => storePin(pin)}`, but then you need to provide your storage mechanism.

**Comment by Haskkor** [comment]
Hey!

Thanks @Panda-ref :). That's how it's suppose to work indeed. 
If you were thinking of something different @mikecann, please tell me :).

Cheers

**Comment by mikecann** [comment]
@Haskkor Well no I was hoping that that I could use the internal storage mechanism and still have a way to navigate to the next screen once the user has chosen their pin code. 

As far as I can tell there is no way of navigating to the next screen?

Ill do a PR to add this in, maybe it will make more sense.

**Comment by Haskkor** [comment]
It makes sense. I'm keen on doing it if you don't have time to do this. Tell me :)

**Comment by mikecann** [comment]
@Haskkor I just did it on my fork, but running into some issues while trying to test it locally (React-Native) caching issues, so either you can take a look at the PR and edit it (and test it) or do it yourself I dont mind :)

**Comment by Haskkor** [comment]
Nice :). I'm closing this issue and testing the PR later today. Thanks again.
