### ISSUE TITLE
Android ApplicationLocked screen positioning issue

### ISSUE THREAD

**Issue by Panda-ref** [Haskkor/react-native-pincode#14]
Original ApplicationLocked render function is:
```
  render() {
    return (
      <View>
        {this.renderErrorLocked()}
      </View>
    )
  }
```
Here we apply container styles on top View component of renderErrorLocked, on Android it still remains hidden despite absolute positioning and you see PinCodeEnter.

Moving container styles here solves the issue for me:
```
  render() {
    return (
      <View style={styles.container}>
        {this.renderErrorLocked()}
      </View>
    )
  }
```

**Comment by Haskkor** [comment]
I've encountered this a lot of time with android.
If you use absolute positioning on an element that would be out of the parent view, it'll stay hidden (don't know if I'm clear enough :p).
We use this component with react navigation to go to the next screen. 

I really don't think I can do something to fix this but if you have an idea...I'm more than keen to hear it :).

Cheers
