### ISSUE TITLE
Delete button text

### ISSUE THREAD

**Issue by gish94** [Haskkor/react-native-pincode#19]
How i can change delete button text only ?
I want to change delete button text, and keep same Icon.

**Comment by Haskkor** [comment]
Hi!

I added a `buttonDeleteText` property in the new version (1.5.2).

Cheers

**Comment by Toshihiro2010** [comment]
but icon show , i want not show icon

**Comment by Haskkor** [comment]
I've added a `iconButtonDeleteDisabled` prop in the new version.

Cheers
