### ISSUE TITLE
TouchId.authenticate was called with 2 arguments but expects 3 arguments (iOS)

### ISSUE THREAD

**Issue by johakr** [Haskkor/react-native-pincode#20]
![simulator screen shot - iphone x - 2018-07-18 at 10 06 09](https://user-images.githubusercontent.com/10597806/42868393-7f4c9e0e-8a72-11e8-82d3-e7d4aa002075.png)

react-native-pincode@v1.5.2
react-native-touch-id@4.0.4
react-native@0.54.4

Keep up the good work. 👍

**Comment by johakr** [comment]
Okay, problem is with requiring `4.0.4` of react-native-touch-id since react-native-pincode requires `gazaret/react-native-touch-id#a7eefb70c0e01ec1036e9026c73221b520d46577`.

Would you consider upgrading react-native-touch-id to 4.0.4? The commit you are referencing should have landed in 4.0.4 already.

**Comment by Haskkor** [comment]
Hi!

You're right it's fixed on 4.0.4. Thanks for letting me know!
I'm releasing a new version right now.

Cheers
