### ISSUE TITLE
pinStatus

### ISSUE THREAD

**Issue by Antlitz** [Haskkor/react-native-pincode#4]
after Locked screen goes away, password not resetted and have unlimited length.

I dont use handler, only required props.

iPhone X simulator.

by the way, why so bad customization? awesome component :)

**Comment by Haskkor** [comment]
Hi.

I fixed the password not resetting but I don't understand the unlimited length issue.
I'll work on making style props over the weekend :).

Cheers

**Comment by Antlitz** [comment]
@Haskkor  also ur package cause error on my device

![image](https://user-images.githubusercontent.com/16013828/41758992-a863fe82-75f4-11e8-92e5-45512df4441c.png)

:(

**Comment by Haskkor** [comment]
I can't reproduce it. I tried with several devices and it's working.
Can you think of a way to help me reproduce it? 
Also I'm working on the style props, should be ready soon :)
