### ISSUE TITLE
Remove "// to do replace" shown from ApplicationLocked.js

### ISSUE THREAD

**Issue by Shaita-KrZ** [Haskkor/react-native-pincode#5]
The textDescriptionLockedPage property is prefixed by // todo replace.

<img width="296" alt="screen shot 2018-06-24 at 4 44 56 pm" src="https://user-images.githubusercontent.com/11573982/41824969-f1a21892-77cd-11e8-9a0a-06a691aa3009.png">

**Comment by Haskkor** [comment]
Comment is only on the code I'm currently working on. Not on the released one. Will be removed soon.
