### ISSUE TITLE
passwordLength issue

### ISSUE THREAD

**Issue by elbertvaldian** [Haskkor/react-native-pincode#7]
hi,

i dont know if it is bug or not, if i set passwordLength to 6, i can type over 6 char. it means if user typed to 8 char accidentally, user need to backspace 2 more extra. Sorry for my bad english, i hope you understand what i mean.

and so, which options can i use to run function if user already type 6 chars, so user cant typed 7th and 8th char.

thanks

**Comment by elbertvaldian** [comment]
and so, i think you need to share the example you make. so the newbies like me can use your library.
hope all the best for you my friend

**Comment by Haskkor** [comment]
Hi :).

I fully get what you mean but I don't see how it can happen. 
I just try with really basic configuration:

In `choose` mode:

```
<PINCode status={'choose'} passwordLength={6}/>
```

I get to enter 5 digits and on the 6th one it'll bring me to the`confirm` page.
On the config page I can enter 6 digits before they all get disabled (you can then show the user to your other pages).

In `enter` mode: 

```
<PINCode status={'enter'} passwordLength={6}/>
```

I can enter 5 digits and on the 6th one
- if the pin is incorrect it'll trigger the error and empty the pin
- if the pin is correct they all get disabled (you can then show the user to your other pages)

Can you tell me when you manage to enter 8 digits so I can try to reproduce it?

Cheers!

**Comment by Haskkor** [comment]
Hey!

So you had it almost right but the passwordLength should be a number not a string :).

```
        <PINCode
          colorPassword={'#e19518'}
          passwordLength={6}
          // stylePinCodeButtonCircle = {{alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(242, 245, 251,0.5)'}}
          // styleLockScreenTextButton
          numbersButtonOverlayColor={'#e19518'}
          titleChoose={'Set Pin Code'}
          subtitleChoose={''}
          finishProcess={this._onPressButton}
          handleResultEnterPin={this._onPressButton}
          status={'choose'} />
```

With this it's working fine. 

Cheers

**Comment by elbertvaldian** [comment]
LOL, my bad.

thanks for your help
