### ISSUE TITLE
 Title and subtitle colors

### ISSUE THREAD

**Issue by stephenkopylov** [Haskkor/react-native-pincode#9]
Hello @Haskkor 

Can't find a way to change title and subtitle colors. 

<img width="407" alt="screen shot 2018-07-05 at 6 24 24 pm" src="https://user-images.githubusercontent.com/5202281/42332495-c95097f4-8080-11e8-9a8a-3b9d3c0a6ede.png">

Could you please add this to props?

**Comment by Haskkor** [comment]
Hi!

I just released a new version with 4 new props:

```
stylePinCodeColorSubtitle: Color of the subtitle in normal state
stylePinCodeColorSubtitleError | Color of the subtitle in error state
stylePinCodeColorTitle | Color of the title in normal state
stylePinCodeColorTitleError | Color of the title in error state
```

Thanks for the feedback.

Cheers

**Comment by stephenkopylov** [comment]
@Haskkor 
Works perfectly, thank you!

It's reasonable, I think, to do the same with "colorPassword", to do "colorPasswordError" or something like this.
Because now dots color with incorrect password is just red. It would be perfect to have a way to change it to the same color like stylePinCodeColorTitleError/stylePinCodeColorSubtitleError =)

**Comment by stephenkopylov** [comment]
@Haskkor 
Thank you! Works perfect!

I made a pull request with addition of incorrect color for dots and colors (common/selected) for circle buttons title 
https://github.com/Haskkor/react-native-pincode/pull/10

**Comment by Haskkor** [comment]
Nice! Thanks a lot! :)
